### PR TITLE
inline options, code refactoring and documentation updated

### PR DESCRIPTION
**Pull request by andreasonny83**
- code refactoring
- inline option
- documentation update

### CODE REVIEW

**Comment by princed** [comment]
Wow. Looks like next major version. 
Do you think we need such an option for footer as well?

**Comment by andreasonny83** [comment]
I'm glad you like my proposal. The inline option affects to both header and footer comments when specified

**Comment by andreasonny83** [comment]
Please, let me know if you're going to accept this PR and tag a new version to it anytime soon as I'm working on a project that will benefits from having that implementation. This is the project I'm working on: https://github.com/andreasonny83/mdl-starter-kit

**Comment by princed** [comment]
I'm reviewing it right now.

**Comment by andreasonny83** [comment]
cool, thanks. Looking forward to that

**Comment by princed** [comment]
I've changed API slightly (see the README) and published as 2.0.0

**Pull request merged**
